{% set version = "5.0.1" %}

package:
  name: svg.path
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/svg.path/svg.path-{{ version }}.tar.gz
  sha256: f269c3ba2186bd483654aa53bee0f3b917104a5bebc98b03678da6f5b8180526

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - svg
    - svg.path
  commands:
    - pip check
    - pytest --pyargs svg.path --cov svg.path --cov-fail-under 97
  requires:
    - pip
    - pytest-cov
    - pillow

about:
  home: https://github.com/regebro/svg.path
  summary: SVG path objects and parser
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
