{% set version = "6.1" %}

package:
  name: svg.path
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/svg.path/svg.path-{{ version }}.tar.gz
  sha256: 8b4471dfb7361b089b66cb42da964158ed00e9a5ca115b8a69ac4f5dc2474a3f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - svg
    - svg.path
  commands:
    - pip check
    - pytest --pyargs svg.path --cov svg.path -k "not test_image" --cov-report term-missing:skip-covered --cov-fail-under 91
  requires:
    - pillow
    - pip
    - pytest-cov

about:
  home: https://github.com/regebro/svg.path
  summary: SVG path objects and parser
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
