{% set version = "6.2" %}

package:
  name: svg.path
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/svg.path/svg.path-{{ version }}.tar.gz
  sha256: 1a2159f9db898df93c4637cfd3ccaf7da1fd073f59fa9a5950c73e46d4aa1aca

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - svg
    - svg.path
  commands:
    - pip check
    - pytest -vv --pyargs svg.path --cov svg.path -k "not (test_image or test_doc)" --cov-report term-missing:skip-covered --cov-fail-under 91
  requires:
    - pillow
    - pip
    - pytest-cov

about:
  home: https://github.com/regebro/svg.path
  summary: SVG path objects and parser
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
