{% set name = "svg.path" %}
{% set version = "5.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c7791d7e578b8a0c942c15d08aa0d7c46c7a1df153d4eaa2ed667a7962a354c2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - svg
    - svg.path
  commands:
    - pip check
    - pytest --pyargs svg.path --cov svg.path --cov-fail-under 97
  requires:
    - pip
    - pytest-cov

about:
  home: https://github.com/regebro/svg.path
  summary: SVG path objects and parser
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
