{% set name = "svg.py" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/svg.py-{{ version }}.tar.gz
  sha256: 2380a7887d26e8057294ce49ddf417c5aa02e4e72eaaf6facb9b4f6f16697b3e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=2,<4
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - typing_extensions

test:
  imports:
    - svg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/orsinium-labs/svg
  summary: SVG drawing library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
