{% set name = "svg.path" %}
{% set version = "4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e6847ba690ff620e20f152818d52e1685b993aacbc41b321f8fee3d1cb427db

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - svg
    - svg.path
  commands:
    - pip check
    - pytest --pyargs svg.path --cov svg.path --cov-fail-under 97
  requires:
    - pip
    - pytest-cov

about:
  home: https://github.com/regebro/svg.path
  summary: SVG path objects and parser
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
