{% set name = "svg.path" %}
{% set version = "5.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: c7791d7e578b8a0c942c15d08aa0d7c46c7a1df153d4eaa2ed667a7962a354c2
  # TODO: remove after https://github.com/regebro/svg.path/pull/79
  - fn: src/svg/path/tests/din1451e.ttf
    url: https://github.com/regebro/svg.path/raw/{{ version }}/src/svg/path/tests/din1451e.ttf
    sha256: 8de62051b842c414018e66459bc0a2a46b480a338ad854fde976576321a7a230

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - svg
    - svg.path
  commands:
    - pip check
    - pytest --pyargs svg.path --cov svg.path --cov-fail-under 97
  requires:
    - pip
    - pytest-cov
    - pillow

about:
  home: https://github.com/regebro/svg.path
  summary: SVG path objects and parser
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
